import os
import pandas as pd

class Olist:
    def get_data(self):
        """
        Returns a dictionary of pandas DataFrames loaded from CSV files.
        Keys are generated by stripping 'olist_' prefix and '_dataset' suffix from filenames.
        """
        # Build absolute path to CSV folder
        csv_path = os.path.join(os.path.dirname(__file__), "..", "data", "csv")
        csv_path = os.path.abspath(csv_path)

        # Verify folder exists
        if not os.path.exists(csv_path):
            raise FileNotFoundError(f"CSV folder not found: {csv_path}")

        # List all CSV files
        file_names = [f for f in os.listdir(csv_path) if f.endswith(".csv")]

        # Create keys from file names
        key_names = [
            f.split('.')[0].replace('olist_', '').replace('_dataset', '')
            for f in file_names
        ]

        # Load CSVs into a dictionary
        data = {}
        for key, file in zip(key_names, file_names):
            data[key] = pd.read_csv(os.path.join(csv_path, file))

        return data

    def ping(self):
        """Simple test method."""
        print("pong")
